<?xml version="1.0" encoding="utf-8"?><Database Name="DSA_SOFD_DB" Class="DSA_SOFDDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=dbsrv_sofd_db;Initial Catalog=DSA_SOFD_DB;Persist Security Info=True;User ID=dsa_sofd_read" SettingsObjectName="DAL_old.Properties.Settings" SettingsPropertyName="DSA_SOFD_DBConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="OPUS.OrgUnit" Member="OrgUnits">
    <Type Name="OrgUnit">
      <Column Name="lastChanged" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="client" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="startDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="endDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="parentOrgUnit" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="shortName" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="longName" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="street" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="addressSupplement" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="zipCode" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="city" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="phoneNumber" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="cvrNr" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="eanNr" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="seNr" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="pNr" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="costCenter" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="orgType" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="orgTypeTxt" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="OrgNveau" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="OPUS.FerieSaldo" Member="FerieSaldos">
    <Type Name="FerieSaldo">
      <Column Name="KommuneInfo" Type="System.String" DbType="VarChar(9)" CanBeNull="true" />
      <Column Name="CPR" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="ANS_FORHOLD_NR" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="Afloenningsform" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="Ferieoptjeningsaar" Type="System.String" DbType="VarChar(4)" CanBeNull="true" />
      <Column Name="DatoForSaldo" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="FerieTimer_MLoen" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EVTFerieDage_MLoen" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FerieTimer_ULoen" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EVTFerieDage_ULoen" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Overfoertetimer" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EvtOverfoertedage" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FERIEFRIDAGSTIMER_SUM" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.v_emps" Member="v_emps">
    <Type Name="v_emp">
      <Column Name="employee_Id" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="lastChanged" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="opus_medid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="client" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="entryDate" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="leaveDate" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="firstName" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="lastName" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="workContract" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="workContractText" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="positionId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="position" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="invoiceRecipient" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="invoiceLevel1" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="invoiceLevel1Text" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="invoiceLevel2" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="invoiceLevel2Text" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="productionNumber" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="isManager" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="orgUnit" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="payGradeText" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="numerator" Type="System.Decimal" DbType="Decimal(28,10)" CanBeNull="true" />
      <Column Name="denominator" Type="System.Decimal" DbType="Decimal(28,10)" CanBeNull="true" />
      <Column Name="initialEntry" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="entryIntoGroup" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="cprnr" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="postalCode" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="city" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="adress" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.v_functions" Member="v_functions">
    <Type Name="v_function">
      <Column Name="startDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="endDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="artId" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="orgDaekning" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="artText" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="members" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="roleId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="roleText" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="opus_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>