#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL_old.DSA_SOFD
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DSA_SOFD_DB")]
	public partial class DSA_SOFDDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public DSA_SOFDDataContext() : 
				base(global::DAL_old.Properties.Settings.Default.DSA_SOFD_DBConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public DSA_SOFDDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DSA_SOFDDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DSA_SOFDDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DSA_SOFDDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<OrgUnit> OrgUnits
		{
			get
			{
				return this.GetTable<OrgUnit>();
			}
		}
		
		public System.Data.Linq.Table<FerieSaldo> FerieSaldos
		{
			get
			{
				return this.GetTable<FerieSaldo>();
			}
		}
		
		public System.Data.Linq.Table<v_emp> v_emps
		{
			get
			{
				return this.GetTable<v_emp>();
			}
		}
		
		public System.Data.Linq.Table<v_function> v_functions
		{
			get
			{
				return this.GetTable<v_function>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="OPUS.OrgUnit")]
	public partial class OrgUnit
	{
		
		private System.Nullable<System.DateTime> _lastChanged;
		
		private System.Nullable<int> _id;
		
		private System.Nullable<short> _client;
		
		private System.Nullable<System.DateTime> _startDate;
		
		private System.Nullable<System.DateTime> _endDate;
		
		private string _parentOrgUnit;
		
		private string _shortName;
		
		private string _longName;
		
		private string _street;
		
		private string _addressSupplement;
		
		private System.Nullable<short> _zipCode;
		
		private string _city;
		
		private string _phoneNumber;
		
		private System.Nullable<int> _cvrNr;
		
		private System.Nullable<long> _eanNr;
		
		private System.Nullable<int> _seNr;
		
		private System.Nullable<int> _pNr;
		
		private System.Nullable<long> _costCenter;
		
		private System.Nullable<short> _orgType;
		
		private string _orgTypeTxt;
		
		private System.Nullable<int> _OrgNveau;
		
		public OrgUnit()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lastChanged", DbType="DateTime")]
		public System.Nullable<System.DateTime> lastChanged
		{
			get
			{
				return this._lastChanged;
			}
			set
			{
				if ((this._lastChanged != value))
				{
					this._lastChanged = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int")]
		public System.Nullable<int> id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_client", DbType="SmallInt")]
		public System.Nullable<short> client
		{
			get
			{
				return this._client;
			}
			set
			{
				if ((this._client != value))
				{
					this._client = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_startDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> startDate
		{
			get
			{
				return this._startDate;
			}
			set
			{
				if ((this._startDate != value))
				{
					this._startDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_endDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> endDate
		{
			get
			{
				return this._endDate;
			}
			set
			{
				if ((this._endDate != value))
				{
					this._endDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_parentOrgUnit", DbType="NVarChar(255)")]
		public string parentOrgUnit
		{
			get
			{
				return this._parentOrgUnit;
			}
			set
			{
				if ((this._parentOrgUnit != value))
				{
					this._parentOrgUnit = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_shortName", DbType="NVarChar(255)")]
		public string shortName
		{
			get
			{
				return this._shortName;
			}
			set
			{
				if ((this._shortName != value))
				{
					this._shortName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_longName", DbType="NVarChar(255)")]
		public string longName
		{
			get
			{
				return this._longName;
			}
			set
			{
				if ((this._longName != value))
				{
					this._longName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_street", DbType="NVarChar(255)")]
		public string street
		{
			get
			{
				return this._street;
			}
			set
			{
				if ((this._street != value))
				{
					this._street = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_addressSupplement", DbType="NVarChar(255)")]
		public string addressSupplement
		{
			get
			{
				return this._addressSupplement;
			}
			set
			{
				if ((this._addressSupplement != value))
				{
					this._addressSupplement = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_zipCode", DbType="SmallInt")]
		public System.Nullable<short> zipCode
		{
			get
			{
				return this._zipCode;
			}
			set
			{
				if ((this._zipCode != value))
				{
					this._zipCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_city", DbType="NVarChar(255)")]
		public string city
		{
			get
			{
				return this._city;
			}
			set
			{
				if ((this._city != value))
				{
					this._city = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phoneNumber", DbType="NVarChar(255)")]
		public string phoneNumber
		{
			get
			{
				return this._phoneNumber;
			}
			set
			{
				if ((this._phoneNumber != value))
				{
					this._phoneNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cvrNr", DbType="Int")]
		public System.Nullable<int> cvrNr
		{
			get
			{
				return this._cvrNr;
			}
			set
			{
				if ((this._cvrNr != value))
				{
					this._cvrNr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_eanNr", DbType="BigInt")]
		public System.Nullable<long> eanNr
		{
			get
			{
				return this._eanNr;
			}
			set
			{
				if ((this._eanNr != value))
				{
					this._eanNr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_seNr", DbType="Int")]
		public System.Nullable<int> seNr
		{
			get
			{
				return this._seNr;
			}
			set
			{
				if ((this._seNr != value))
				{
					this._seNr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pNr", DbType="Int")]
		public System.Nullable<int> pNr
		{
			get
			{
				return this._pNr;
			}
			set
			{
				if ((this._pNr != value))
				{
					this._pNr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_costCenter", DbType="BigInt")]
		public System.Nullable<long> costCenter
		{
			get
			{
				return this._costCenter;
			}
			set
			{
				if ((this._costCenter != value))
				{
					this._costCenter = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_orgType", DbType="SmallInt")]
		public System.Nullable<short> orgType
		{
			get
			{
				return this._orgType;
			}
			set
			{
				if ((this._orgType != value))
				{
					this._orgType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_orgTypeTxt", DbType="NVarChar(255)")]
		public string orgTypeTxt
		{
			get
			{
				return this._orgTypeTxt;
			}
			set
			{
				if ((this._orgTypeTxt != value))
				{
					this._orgTypeTxt = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrgNveau", DbType="Int")]
		public System.Nullable<int> OrgNveau
		{
			get
			{
				return this._OrgNveau;
			}
			set
			{
				if ((this._OrgNveau != value))
				{
					this._OrgNveau = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="OPUS.FerieSaldo")]
	public partial class FerieSaldo
	{
		
		private string _KommuneInfo;
		
		private string _CPR;
		
		private string _ANS_FORHOLD_NR;
		
		private string _Afloenningsform;
		
		private string _Ferieoptjeningsaar;
		
		private string _DatoForSaldo;
		
		private System.Nullable<int> _FerieTimer_MLoen;
		
		private System.Nullable<int> _EVTFerieDage_MLoen;
		
		private System.Nullable<int> _FerieTimer_ULoen;
		
		private System.Nullable<int> _EVTFerieDage_ULoen;
		
		private System.Nullable<int> _Overfoertetimer;
		
		private System.Nullable<int> _EvtOverfoertedage;
		
		private System.Nullable<int> _FERIEFRIDAGSTIMER_SUM;
		
		public FerieSaldo()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KommuneInfo", DbType="VarChar(9)")]
		public string KommuneInfo
		{
			get
			{
				return this._KommuneInfo;
			}
			set
			{
				if ((this._KommuneInfo != value))
				{
					this._KommuneInfo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CPR", DbType="VarChar(10)")]
		public string CPR
		{
			get
			{
				return this._CPR;
			}
			set
			{
				if ((this._CPR != value))
				{
					this._CPR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ANS_FORHOLD_NR", DbType="VarChar(1)")]
		public string ANS_FORHOLD_NR
		{
			get
			{
				return this._ANS_FORHOLD_NR;
			}
			set
			{
				if ((this._ANS_FORHOLD_NR != value))
				{
					this._ANS_FORHOLD_NR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Afloenningsform", DbType="VarChar(1)")]
		public string Afloenningsform
		{
			get
			{
				return this._Afloenningsform;
			}
			set
			{
				if ((this._Afloenningsform != value))
				{
					this._Afloenningsform = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ferieoptjeningsaar", DbType="VarChar(4)")]
		public string Ferieoptjeningsaar
		{
			get
			{
				return this._Ferieoptjeningsaar;
			}
			set
			{
				if ((this._Ferieoptjeningsaar != value))
				{
					this._Ferieoptjeningsaar = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DatoForSaldo", DbType="VarChar(10)")]
		public string DatoForSaldo
		{
			get
			{
				return this._DatoForSaldo;
			}
			set
			{
				if ((this._DatoForSaldo != value))
				{
					this._DatoForSaldo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FerieTimer_MLoen", DbType="Int")]
		public System.Nullable<int> FerieTimer_MLoen
		{
			get
			{
				return this._FerieTimer_MLoen;
			}
			set
			{
				if ((this._FerieTimer_MLoen != value))
				{
					this._FerieTimer_MLoen = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EVTFerieDage_MLoen", DbType="Int")]
		public System.Nullable<int> EVTFerieDage_MLoen
		{
			get
			{
				return this._EVTFerieDage_MLoen;
			}
			set
			{
				if ((this._EVTFerieDage_MLoen != value))
				{
					this._EVTFerieDage_MLoen = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FerieTimer_ULoen", DbType="Int")]
		public System.Nullable<int> FerieTimer_ULoen
		{
			get
			{
				return this._FerieTimer_ULoen;
			}
			set
			{
				if ((this._FerieTimer_ULoen != value))
				{
					this._FerieTimer_ULoen = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EVTFerieDage_ULoen", DbType="Int")]
		public System.Nullable<int> EVTFerieDage_ULoen
		{
			get
			{
				return this._EVTFerieDage_ULoen;
			}
			set
			{
				if ((this._EVTFerieDage_ULoen != value))
				{
					this._EVTFerieDage_ULoen = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Overfoertetimer", DbType="Int")]
		public System.Nullable<int> Overfoertetimer
		{
			get
			{
				return this._Overfoertetimer;
			}
			set
			{
				if ((this._Overfoertetimer != value))
				{
					this._Overfoertetimer = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EvtOverfoertedage", DbType="Int")]
		public System.Nullable<int> EvtOverfoertedage
		{
			get
			{
				return this._EvtOverfoertedage;
			}
			set
			{
				if ((this._EvtOverfoertedage != value))
				{
					this._EvtOverfoertedage = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FERIEFRIDAGSTIMER_SUM", DbType="Int")]
		public System.Nullable<int> FERIEFRIDAGSTIMER_SUM
		{
			get
			{
				return this._FERIEFRIDAGSTIMER_SUM;
			}
			set
			{
				if ((this._FERIEFRIDAGSTIMER_SUM != value))
				{
					this._FERIEFRIDAGSTIMER_SUM = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.v_emps")]
	public partial class v_emp
	{
		
		private System.Nullable<decimal> _employee_Id;
		
		private System.Nullable<System.DateTime> _lastChanged;
		
		private System.Nullable<int> _opus_medid;
		
		private System.Nullable<short> _client;
		
		private string _entryDate;
		
		private string _leaveDate;
		
		private string _firstName;
		
		private string _lastName;
		
		private string _workContract;
		
		private string _workContractText;
		
		private System.Nullable<int> _positionId;
		
		private string _position;
		
		private System.Nullable<bool> _invoiceRecipient;
		
		private string _invoiceLevel1;
		
		private string _invoiceLevel1Text;
		
		private string _invoiceLevel2;
		
		private string _invoiceLevel2Text;
		
		private string _productionNumber;
		
		private System.Nullable<bool> _isManager;
		
		private System.Nullable<int> _orgUnit;
		
		private string _payGradeText;
		
		private System.Nullable<decimal> _numerator;
		
		private System.Nullable<decimal> _denominator;
		
		private string _initialEntry;
		
		private string _entryIntoGroup;
		
		private string _cprnr;
		
		private string _postalCode;
		
		private string _city;
		
		private string _adress;
		
		public v_emp()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_employee_Id", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> employee_Id
		{
			get
			{
				return this._employee_Id;
			}
			set
			{
				if ((this._employee_Id != value))
				{
					this._employee_Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lastChanged", DbType="DateTime")]
		public System.Nullable<System.DateTime> lastChanged
		{
			get
			{
				return this._lastChanged;
			}
			set
			{
				if ((this._lastChanged != value))
				{
					this._lastChanged = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_opus_medid", DbType="Int")]
		public System.Nullable<int> opus_medid
		{
			get
			{
				return this._opus_medid;
			}
			set
			{
				if ((this._opus_medid != value))
				{
					this._opus_medid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_client", DbType="SmallInt")]
		public System.Nullable<short> client
		{
			get
			{
				return this._client;
			}
			set
			{
				if ((this._client != value))
				{
					this._client = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_entryDate", DbType="NVarChar(255)")]
		public string entryDate
		{
			get
			{
				return this._entryDate;
			}
			set
			{
				if ((this._entryDate != value))
				{
					this._entryDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_leaveDate", DbType="NVarChar(255)")]
		public string leaveDate
		{
			get
			{
				return this._leaveDate;
			}
			set
			{
				if ((this._leaveDate != value))
				{
					this._leaveDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_firstName", DbType="NVarChar(255)")]
		public string firstName
		{
			get
			{
				return this._firstName;
			}
			set
			{
				if ((this._firstName != value))
				{
					this._firstName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lastName", DbType="NVarChar(255)")]
		public string lastName
		{
			get
			{
				return this._lastName;
			}
			set
			{
				if ((this._lastName != value))
				{
					this._lastName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_workContract", DbType="NVarChar(255)")]
		public string workContract
		{
			get
			{
				return this._workContract;
			}
			set
			{
				if ((this._workContract != value))
				{
					this._workContract = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_workContractText", DbType="NVarChar(255)")]
		public string workContractText
		{
			get
			{
				return this._workContractText;
			}
			set
			{
				if ((this._workContractText != value))
				{
					this._workContractText = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_positionId", DbType="Int")]
		public System.Nullable<int> positionId
		{
			get
			{
				return this._positionId;
			}
			set
			{
				if ((this._positionId != value))
				{
					this._positionId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_position", DbType="NVarChar(255)")]
		public string position
		{
			get
			{
				return this._position;
			}
			set
			{
				if ((this._position != value))
				{
					this._position = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_invoiceRecipient", DbType="Bit")]
		public System.Nullable<bool> invoiceRecipient
		{
			get
			{
				return this._invoiceRecipient;
			}
			set
			{
				if ((this._invoiceRecipient != value))
				{
					this._invoiceRecipient = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_invoiceLevel1", DbType="NVarChar(255)")]
		public string invoiceLevel1
		{
			get
			{
				return this._invoiceLevel1;
			}
			set
			{
				if ((this._invoiceLevel1 != value))
				{
					this._invoiceLevel1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_invoiceLevel1Text", DbType="NVarChar(255)")]
		public string invoiceLevel1Text
		{
			get
			{
				return this._invoiceLevel1Text;
			}
			set
			{
				if ((this._invoiceLevel1Text != value))
				{
					this._invoiceLevel1Text = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_invoiceLevel2", DbType="NVarChar(255)")]
		public string invoiceLevel2
		{
			get
			{
				return this._invoiceLevel2;
			}
			set
			{
				if ((this._invoiceLevel2 != value))
				{
					this._invoiceLevel2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_invoiceLevel2Text", DbType="NVarChar(255)")]
		public string invoiceLevel2Text
		{
			get
			{
				return this._invoiceLevel2Text;
			}
			set
			{
				if ((this._invoiceLevel2Text != value))
				{
					this._invoiceLevel2Text = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_productionNumber", DbType="NVarChar(255)")]
		public string productionNumber
		{
			get
			{
				return this._productionNumber;
			}
			set
			{
				if ((this._productionNumber != value))
				{
					this._productionNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isManager", DbType="Bit")]
		public System.Nullable<bool> isManager
		{
			get
			{
				return this._isManager;
			}
			set
			{
				if ((this._isManager != value))
				{
					this._isManager = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_orgUnit", DbType="Int")]
		public System.Nullable<int> orgUnit
		{
			get
			{
				return this._orgUnit;
			}
			set
			{
				if ((this._orgUnit != value))
				{
					this._orgUnit = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_payGradeText", DbType="NVarChar(255)")]
		public string payGradeText
		{
			get
			{
				return this._payGradeText;
			}
			set
			{
				if ((this._payGradeText != value))
				{
					this._payGradeText = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numerator", DbType="Decimal(28,10)")]
		public System.Nullable<decimal> numerator
		{
			get
			{
				return this._numerator;
			}
			set
			{
				if ((this._numerator != value))
				{
					this._numerator = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_denominator", DbType="Decimal(28,10)")]
		public System.Nullable<decimal> denominator
		{
			get
			{
				return this._denominator;
			}
			set
			{
				if ((this._denominator != value))
				{
					this._denominator = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_initialEntry", DbType="NVarChar(255)")]
		public string initialEntry
		{
			get
			{
				return this._initialEntry;
			}
			set
			{
				if ((this._initialEntry != value))
				{
					this._initialEntry = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_entryIntoGroup", DbType="NVarChar(255)")]
		public string entryIntoGroup
		{
			get
			{
				return this._entryIntoGroup;
			}
			set
			{
				if ((this._entryIntoGroup != value))
				{
					this._entryIntoGroup = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cprnr", DbType="NVarChar(255)")]
		public string cprnr
		{
			get
			{
				return this._cprnr;
			}
			set
			{
				if ((this._cprnr != value))
				{
					this._cprnr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_postalCode", DbType="NVarChar(255)")]
		public string postalCode
		{
			get
			{
				return this._postalCode;
			}
			set
			{
				if ((this._postalCode != value))
				{
					this._postalCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_city", DbType="NVarChar(255)")]
		public string city
		{
			get
			{
				return this._city;
			}
			set
			{
				if ((this._city != value))
				{
					this._city = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_adress", DbType="NVarChar(255)")]
		public string adress
		{
			get
			{
				return this._adress;
			}
			set
			{
				if ((this._adress != value))
				{
					this._adress = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.v_functions")]
	public partial class v_function
	{
		
		private System.Nullable<System.DateTime> _startDate;
		
		private System.Nullable<System.DateTime> _endDate;
		
		private System.Nullable<short> _artId;
		
		private string _orgDaekning;
		
		private string _artText;
		
		private System.Nullable<int> _members;
		
		private System.Nullable<int> _roleId;
		
		private string _roleText;
		
		private System.Nullable<int> _opus_id;
		
		public v_function()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_startDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> startDate
		{
			get
			{
				return this._startDate;
			}
			set
			{
				if ((this._startDate != value))
				{
					this._startDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_endDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> endDate
		{
			get
			{
				return this._endDate;
			}
			set
			{
				if ((this._endDate != value))
				{
					this._endDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_artId", DbType="SmallInt")]
		public System.Nullable<short> artId
		{
			get
			{
				return this._artId;
			}
			set
			{
				if ((this._artId != value))
				{
					this._artId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_orgDaekning", DbType="NVarChar(255)")]
		public string orgDaekning
		{
			get
			{
				return this._orgDaekning;
			}
			set
			{
				if ((this._orgDaekning != value))
				{
					this._orgDaekning = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_artText", DbType="NVarChar(255)")]
		public string artText
		{
			get
			{
				return this._artText;
			}
			set
			{
				if ((this._artText != value))
				{
					this._artText = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_members", DbType="Int")]
		public System.Nullable<int> members
		{
			get
			{
				return this._members;
			}
			set
			{
				if ((this._members != value))
				{
					this._members = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_roleId", DbType="Int")]
		public System.Nullable<int> roleId
		{
			get
			{
				return this._roleId;
			}
			set
			{
				if ((this._roleId != value))
				{
					this._roleId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_roleText", DbType="NVarChar(255)")]
		public string roleText
		{
			get
			{
				return this._roleText;
			}
			set
			{
				if ((this._roleText != value))
				{
					this._roleText = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_opus_id", DbType="Int")]
		public System.Nullable<int> opus_id
		{
			get
			{
				return this._opus_id;
			}
			set
			{
				if ((this._opus_id != value))
				{
					this._opus_id = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
