#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL_old.LORA_SOFD
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="LORA_SOFD")]
	public partial class LORA_SOFDDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertAdress(Adress instance);
    partial void UpdateAdress(Adress instance);
    partial void DeleteAdress(Adress instance);
    partial void InsertManager_lookup(Manager_lookup instance);
    partial void UpdateManager_lookup(Manager_lookup instance);
    partial void DeleteManager_lookup(Manager_lookup instance);
    partial void InsertOrgunit(Orgunit instance);
    partial void UpdateOrgunit(Orgunit instance);
    partial void DeleteOrgunit(Orgunit instance);
    partial void InsertPerson(Person instance);
    partial void UpdatePerson(Person instance);
    partial void DeletePerson(Person instance);
    partial void InsertPosition(Position instance);
    partial void UpdatePosition(Position instance);
    partial void DeletePosition(Position instance);
    partial void InsertUser(User instance);
    partial void UpdateUser(User instance);
    partial void DeleteUser(User instance);
    partial void Insertchange(change instance);
    partial void Updatechange(change instance);
    partial void Deletechange(change instance);
    partial void InsertqUser1(qUser1 instance);
    partial void UpdateqUser1(qUser1 instance);
    partial void DeleteqUser1(qUser1 instance);
    partial void InsertqOrgunit(qOrgunit instance);
    partial void UpdateqOrgunit(qOrgunit instance);
    partial void DeleteqOrgunit(qOrgunit instance);
    partial void InsertqUser(qUser instance);
    partial void UpdateqUser(qUser instance);
    partial void DeleteqUser(qUser instance);
    partial void InsertqUsers_AD(qUsers_AD instance);
    partial void UpdateqUsers_AD(qUsers_AD instance);
    partial void DeleteqUsers_AD(qUsers_AD instance);
    #endregion
		
		public LORA_SOFDDataContext() : 
				base(global::DAL_old.Properties.Settings.Default.LORA_SOFDConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public LORA_SOFDDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LORA_SOFDDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LORA_SOFDDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LORA_SOFDDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Adress> Adresses
		{
			get
			{
				return this.GetTable<Adress>();
			}
		}
		
		public System.Data.Linq.Table<Manager_lookup> Manager_lookups
		{
			get
			{
				return this.GetTable<Manager_lookup>();
			}
		}
		
		public System.Data.Linq.Table<Orgunit> Orgunits
		{
			get
			{
				return this.GetTable<Orgunit>();
			}
		}
		
		public System.Data.Linq.Table<Person> Persons
		{
			get
			{
				return this.GetTable<Person>();
			}
		}
		
		public System.Data.Linq.Table<Position> Positions
		{
			get
			{
				return this.GetTable<Position>();
			}
		}
		
		public System.Data.Linq.Table<User> Users
		{
			get
			{
				return this.GetTable<User>();
			}
		}
		
		public System.Data.Linq.Table<change> changes
		{
			get
			{
				return this.GetTable<change>();
			}
		}
		
		public System.Data.Linq.Table<qUser1> qUser1s
		{
			get
			{
				return this.GetTable<qUser1>();
			}
		}
		
		public System.Data.Linq.Table<qOrgunit> qOrgunits
		{
			get
			{
				return this.GetTable<qOrgunit>();
			}
		}
		
		public System.Data.Linq.Table<qUser> qUsers
		{
			get
			{
				return this.GetTable<qUser>();
			}
		}
		
		public System.Data.Linq.Table<qUsers_AD> qUsers_ADs
		{
			get
			{
				return this.GetTable<qUsers_AD>();
			}
		}
		
		public System.Data.Linq.Table<v_sofd_medarbejderoverblik> v_sofd_medarbejderoverbliks
		{
			get
			{
				return this.GetTable<v_sofd_medarbejderoverblik>();
			}
		}
		
		public System.Data.Linq.Table<v_akubiz_employee> v_akubiz_employees
		{
			get
			{
				return this.GetTable<v_akubiz_employee>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Adresses")]
	public partial class Adress : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _system_id;
		
		private string _gade;
		
		private int _postnr;
		
		private string _by;
		
		private EntitySet<Orgunit> _Orgunits;
		
		private EntitySet<Person> _Persons;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onsystem_idChanging(int value);
    partial void Onsystem_idChanged();
    partial void OngadeChanging(string value);
    partial void OngadeChanged();
    partial void OnpostnrChanging(int value);
    partial void OnpostnrChanged();
    partial void OnbyChanging(string value);
    partial void OnbyChanged();
    #endregion
		
		public Adress()
		{
			this._Orgunits = new EntitySet<Orgunit>(new Action<Orgunit>(this.attach_Orgunits), new Action<Orgunit>(this.detach_Orgunits));
			this._Persons = new EntitySet<Person>(new Action<Person>(this.attach_Persons), new Action<Person>(this.detach_Persons));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_system_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int system_id
		{
			get
			{
				return this._system_id;
			}
			set
			{
				if ((this._system_id != value))
				{
					this.Onsystem_idChanging(value);
					this.SendPropertyChanging();
					this._system_id = value;
					this.SendPropertyChanged("system_id");
					this.Onsystem_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gade", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string gade
		{
			get
			{
				return this._gade;
			}
			set
			{
				if ((this._gade != value))
				{
					this.OngadeChanging(value);
					this.SendPropertyChanging();
					this._gade = value;
					this.SendPropertyChanged("gade");
					this.OngadeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_postnr", DbType="Int NOT NULL")]
		public int postnr
		{
			get
			{
				return this._postnr;
			}
			set
			{
				if ((this._postnr != value))
				{
					this.OnpostnrChanging(value);
					this.SendPropertyChanging();
					this._postnr = value;
					this.SendPropertyChanged("postnr");
					this.OnpostnrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[by]", Storage="_by", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string by
		{
			get
			{
				return this._by;
			}
			set
			{
				if ((this._by != value))
				{
					this.OnbyChanging(value);
					this.SendPropertyChanging();
					this._by = value;
					this.SendPropertyChanged("by");
					this.OnbyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Adress_Orgunit", Storage="_Orgunits", ThisKey="system_id", OtherKey="Adress_ref")]
		public EntitySet<Orgunit> Orgunits
		{
			get
			{
				return this._Orgunits;
			}
			set
			{
				this._Orgunits.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Adress_Person", Storage="_Persons", ThisKey="system_id", OtherKey="Private_adr_fk")]
		public EntitySet<Person> Persons
		{
			get
			{
				return this._Persons;
			}
			set
			{
				this._Persons.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Orgunits(Orgunit entity)
		{
			this.SendPropertyChanging();
			entity.Adress = this;
		}
		
		private void detach_Orgunits(Orgunit entity)
		{
			this.SendPropertyChanging();
			entity.Adress = null;
		}
		
		private void attach_Persons(Person entity)
		{
			this.SendPropertyChanging();
			entity.Adress = this;
		}
		
		private void detach_Persons(Person entity)
		{
			this.SendPropertyChanging();
			entity.Adress = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Manager_lookup")]
	public partial class Manager_lookup : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _system_id;
		
		private int _opus_id;
		
		private int _manager_opus_id;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onsystem_idChanging(int value);
    partial void Onsystem_idChanged();
    partial void Onopus_idChanging(int value);
    partial void Onopus_idChanged();
    partial void Onmanager_opus_idChanging(int value);
    partial void Onmanager_opus_idChanged();
    #endregion
		
		public Manager_lookup()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_system_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int system_id
		{
			get
			{
				return this._system_id;
			}
			set
			{
				if ((this._system_id != value))
				{
					this.Onsystem_idChanging(value);
					this.SendPropertyChanging();
					this._system_id = value;
					this.SendPropertyChanged("system_id");
					this.Onsystem_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_opus_id", DbType="Int NOT NULL")]
		public int opus_id
		{
			get
			{
				return this._opus_id;
			}
			set
			{
				if ((this._opus_id != value))
				{
					this.Onopus_idChanging(value);
					this.SendPropertyChanging();
					this._opus_id = value;
					this.SendPropertyChanged("opus_id");
					this.Onopus_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_manager_opus_id", DbType="Int NOT NULL")]
		public int manager_opus_id
		{
			get
			{
				return this._manager_opus_id;
			}
			set
			{
				if ((this._manager_opus_id != value))
				{
					this.Onmanager_opus_idChanging(value);
					this.SendPropertyChanging();
					this._manager_opus_id = value;
					this.SendPropertyChanged("manager_opus_id");
					this.Onmanager_opus_idChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Orgunits")]
	public partial class Orgunit : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _System_id;
		
		private string _Uuid;
		
		private int _Los_id;
		
		private string _Name;
		
		private string _PayoutUnitUuid;
		
		private System.DateTime _Created_date;
		
		private string _Phone;
		
		private string _Email;
		
		private int _Parent_losid;
		
		private string _Los_short_name;
		
		private int _Adress_ref;
		
		private System.DateTime _Last_changed;
		
		private System.Nullable<long> _Ean;
		
		private System.Nullable<long> _Pnr;
		
		private System.Nullable<long> _Cost_center;
		
		private string _Org_type;
		
		private int _Org_niveau;
		
		private EntitySet<Position> _Positions;
		
		private EntityRef<Adress> _Adress;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSystem_idChanging(int value);
    partial void OnSystem_idChanged();
    partial void OnUuidChanging(string value);
    partial void OnUuidChanged();
    partial void OnLos_idChanging(int value);
    partial void OnLos_idChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnPayoutUnitUuidChanging(string value);
    partial void OnPayoutUnitUuidChanged();
    partial void OnCreated_dateChanging(System.DateTime value);
    partial void OnCreated_dateChanged();
    partial void OnPhoneChanging(string value);
    partial void OnPhoneChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnParent_losidChanging(int value);
    partial void OnParent_losidChanged();
    partial void OnLos_short_nameChanging(string value);
    partial void OnLos_short_nameChanged();
    partial void OnAdress_refChanging(int value);
    partial void OnAdress_refChanged();
    partial void OnLast_changedChanging(System.DateTime value);
    partial void OnLast_changedChanged();
    partial void OnEanChanging(System.Nullable<long> value);
    partial void OnEanChanged();
    partial void OnPnrChanging(System.Nullable<long> value);
    partial void OnPnrChanged();
    partial void OnCost_centerChanging(System.Nullable<long> value);
    partial void OnCost_centerChanged();
    partial void OnOrg_typeChanging(string value);
    partial void OnOrg_typeChanged();
    partial void OnOrg_niveauChanging(int value);
    partial void OnOrg_niveauChanged();
    #endregion
		
		public Orgunit()
		{
			this._Positions = new EntitySet<Position>(new Action<Position>(this.attach_Positions), new Action<Position>(this.detach_Positions));
			this._Adress = default(EntityRef<Adress>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_System_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int System_id
		{
			get
			{
				return this._System_id;
			}
			set
			{
				if ((this._System_id != value))
				{
					this.OnSystem_idChanging(value);
					this.SendPropertyChanging();
					this._System_id = value;
					this.SendPropertyChanged("System_id");
					this.OnSystem_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Uuid", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string Uuid
		{
			get
			{
				return this._Uuid;
			}
			set
			{
				if ((this._Uuid != value))
				{
					this.OnUuidChanging(value);
					this.SendPropertyChanging();
					this._Uuid = value;
					this.SendPropertyChanged("Uuid");
					this.OnUuidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Los_id", DbType="Int NOT NULL")]
		public int Los_id
		{
			get
			{
				return this._Los_id;
			}
			set
			{
				if ((this._Los_id != value))
				{
					this.OnLos_idChanging(value);
					this.SendPropertyChanging();
					this._Los_id = value;
					this.SendPropertyChanged("Los_id");
					this.OnLos_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PayoutUnitUuid", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string PayoutUnitUuid
		{
			get
			{
				return this._PayoutUnitUuid;
			}
			set
			{
				if ((this._PayoutUnitUuid != value))
				{
					this.OnPayoutUnitUuidChanging(value);
					this.SendPropertyChanging();
					this._PayoutUnitUuid = value;
					this.SendPropertyChanged("PayoutUnitUuid");
					this.OnPayoutUnitUuidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Created_date", DbType="DateTime NOT NULL")]
		public System.DateTime Created_date
		{
			get
			{
				return this._Created_date;
			}
			set
			{
				if ((this._Created_date != value))
				{
					this.OnCreated_dateChanging(value);
					this.SendPropertyChanging();
					this._Created_date = value;
					this.SendPropertyChanged("Created_date");
					this.OnCreated_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string Phone
		{
			get
			{
				return this._Phone;
			}
			set
			{
				if ((this._Phone != value))
				{
					this.OnPhoneChanging(value);
					this.SendPropertyChanging();
					this._Phone = value;
					this.SendPropertyChanged("Phone");
					this.OnPhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Parent_losid", DbType="Int NOT NULL")]
		public int Parent_losid
		{
			get
			{
				return this._Parent_losid;
			}
			set
			{
				if ((this._Parent_losid != value))
				{
					this.OnParent_losidChanging(value);
					this.SendPropertyChanging();
					this._Parent_losid = value;
					this.SendPropertyChanged("Parent_losid");
					this.OnParent_losidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Los_short_name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Los_short_name
		{
			get
			{
				return this._Los_short_name;
			}
			set
			{
				if ((this._Los_short_name != value))
				{
					this.OnLos_short_nameChanging(value);
					this.SendPropertyChanging();
					this._Los_short_name = value;
					this.SendPropertyChanged("Los_short_name");
					this.OnLos_short_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Adress_ref", DbType="Int NOT NULL")]
		public int Adress_ref
		{
			get
			{
				return this._Adress_ref;
			}
			set
			{
				if ((this._Adress_ref != value))
				{
					if (this._Adress.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnAdress_refChanging(value);
					this.SendPropertyChanging();
					this._Adress_ref = value;
					this.SendPropertyChanged("Adress_ref");
					this.OnAdress_refChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Last_changed", DbType="DateTime NOT NULL")]
		public System.DateTime Last_changed
		{
			get
			{
				return this._Last_changed;
			}
			set
			{
				if ((this._Last_changed != value))
				{
					this.OnLast_changedChanging(value);
					this.SendPropertyChanging();
					this._Last_changed = value;
					this.SendPropertyChanged("Last_changed");
					this.OnLast_changedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ean", DbType="BigInt")]
		public System.Nullable<long> Ean
		{
			get
			{
				return this._Ean;
			}
			set
			{
				if ((this._Ean != value))
				{
					this.OnEanChanging(value);
					this.SendPropertyChanging();
					this._Ean = value;
					this.SendPropertyChanged("Ean");
					this.OnEanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pnr", DbType="BigInt")]
		public System.Nullable<long> Pnr
		{
			get
			{
				return this._Pnr;
			}
			set
			{
				if ((this._Pnr != value))
				{
					this.OnPnrChanging(value);
					this.SendPropertyChanging();
					this._Pnr = value;
					this.SendPropertyChanged("Pnr");
					this.OnPnrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cost_center", DbType="BigInt")]
		public System.Nullable<long> Cost_center
		{
			get
			{
				return this._Cost_center;
			}
			set
			{
				if ((this._Cost_center != value))
				{
					this.OnCost_centerChanging(value);
					this.SendPropertyChanging();
					this._Cost_center = value;
					this.SendPropertyChanged("Cost_center");
					this.OnCost_centerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Org_type", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Org_type
		{
			get
			{
				return this._Org_type;
			}
			set
			{
				if ((this._Org_type != value))
				{
					this.OnOrg_typeChanging(value);
					this.SendPropertyChanging();
					this._Org_type = value;
					this.SendPropertyChanged("Org_type");
					this.OnOrg_typeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Org_niveau", DbType="Int NOT NULL")]
		public int Org_niveau
		{
			get
			{
				return this._Org_niveau;
			}
			set
			{
				if ((this._Org_niveau != value))
				{
					this.OnOrg_niveauChanging(value);
					this.SendPropertyChanging();
					this._Org_niveau = value;
					this.SendPropertyChanged("Org_niveau");
					this.OnOrg_niveauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Orgunit_Position", Storage="_Positions", ThisKey="Los_id", OtherKey="Orgunit_losid_fk")]
		public EntitySet<Position> Positions
		{
			get
			{
				return this._Positions;
			}
			set
			{
				this._Positions.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Adress_Orgunit", Storage="_Adress", ThisKey="Adress_ref", OtherKey="system_id", IsForeignKey=true)]
		public Adress Adress
		{
			get
			{
				return this._Adress.Entity;
			}
			set
			{
				Adress previousValue = this._Adress.Entity;
				if (((previousValue != value) 
							|| (this._Adress.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Adress.Entity = null;
						previousValue.Orgunits.Remove(this);
					}
					this._Adress.Entity = value;
					if ((value != null))
					{
						value.Orgunits.Add(this);
						this._Adress_ref = value.system_id;
					}
					else
					{
						this._Adress_ref = default(int);
					}
					this.SendPropertyChanged("Adress");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Positions(Position entity)
		{
			this.SendPropertyChanging();
			entity.Orgunit = this;
		}
		
		private void detach_Positions(Position entity)
		{
			this.SendPropertyChanging();
			entity.Orgunit = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Persons")]
	public partial class Person : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _System_id;
		
		private string _Name;
		
		private string _Cpr;
		
		private string _Firstname;
		
		private string _Lastname;
		
		private int _Private_adr_fk;
		
		private System.DateTime _Last_changed;
		
		private EntitySet<Position> _Positions;
		
		private EntityRef<Adress> _Adress;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSystem_idChanging(int value);
    partial void OnSystem_idChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnCprChanging(string value);
    partial void OnCprChanged();
    partial void OnFirstnameChanging(string value);
    partial void OnFirstnameChanged();
    partial void OnLastnameChanging(string value);
    partial void OnLastnameChanged();
    partial void OnPrivate_adr_fkChanging(int value);
    partial void OnPrivate_adr_fkChanged();
    partial void OnLast_changedChanging(System.DateTime value);
    partial void OnLast_changedChanged();
    #endregion
		
		public Person()
		{
			this._Positions = new EntitySet<Position>(new Action<Position>(this.attach_Positions), new Action<Position>(this.detach_Positions));
			this._Adress = default(EntityRef<Adress>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_System_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int System_id
		{
			get
			{
				return this._System_id;
			}
			set
			{
				if ((this._System_id != value))
				{
					this.OnSystem_idChanging(value);
					this.SendPropertyChanging();
					this._System_id = value;
					this.SendPropertyChanged("System_id");
					this.OnSystem_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cpr", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Cpr
		{
			get
			{
				return this._Cpr;
			}
			set
			{
				if ((this._Cpr != value))
				{
					this.OnCprChanging(value);
					this.SendPropertyChanging();
					this._Cpr = value;
					this.SendPropertyChanged("Cpr");
					this.OnCprChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Firstname", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Firstname
		{
			get
			{
				return this._Firstname;
			}
			set
			{
				if ((this._Firstname != value))
				{
					this.OnFirstnameChanging(value);
					this.SendPropertyChanging();
					this._Firstname = value;
					this.SendPropertyChanged("Firstname");
					this.OnFirstnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lastname", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Lastname
		{
			get
			{
				return this._Lastname;
			}
			set
			{
				if ((this._Lastname != value))
				{
					this.OnLastnameChanging(value);
					this.SendPropertyChanging();
					this._Lastname = value;
					this.SendPropertyChanged("Lastname");
					this.OnLastnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Private_adr_fk", DbType="Int NOT NULL")]
		public int Private_adr_fk
		{
			get
			{
				return this._Private_adr_fk;
			}
			set
			{
				if ((this._Private_adr_fk != value))
				{
					if (this._Adress.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnPrivate_adr_fkChanging(value);
					this.SendPropertyChanging();
					this._Private_adr_fk = value;
					this.SendPropertyChanged("Private_adr_fk");
					this.OnPrivate_adr_fkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Last_changed", DbType="DateTime NOT NULL")]
		public System.DateTime Last_changed
		{
			get
			{
				return this._Last_changed;
			}
			set
			{
				if ((this._Last_changed != value))
				{
					this.OnLast_changedChanging(value);
					this.SendPropertyChanging();
					this._Last_changed = value;
					this.SendPropertyChanged("Last_changed");
					this.OnLast_changedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Person_Position", Storage="_Positions", ThisKey="Cpr", OtherKey="Person_fk")]
		public EntitySet<Position> Positions
		{
			get
			{
				return this._Positions;
			}
			set
			{
				this._Positions.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Adress_Person", Storage="_Adress", ThisKey="Private_adr_fk", OtherKey="system_id", IsForeignKey=true)]
		public Adress Adress
		{
			get
			{
				return this._Adress.Entity;
			}
			set
			{
				Adress previousValue = this._Adress.Entity;
				if (((previousValue != value) 
							|| (this._Adress.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Adress.Entity = null;
						previousValue.Persons.Remove(this);
					}
					this._Adress.Entity = value;
					if ((value != null))
					{
						value.Persons.Add(this);
						this._Private_adr_fk = value.system_id;
					}
					else
					{
						this._Private_adr_fk = default(int);
					}
					this.SendPropertyChanged("Adress");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Positions(Position entity)
		{
			this.SendPropertyChanging();
			entity.Person = this;
		}
		
		private void detach_Positions(Position entity)
		{
			this.SendPropertyChanging();
			entity.Person = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Positions")]
	public partial class Position : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _System_id;
		
		private int _Opus_id;
		
		private string _Name;
		
		private int _Orgunit_losid_fk;
		
		private string _Person_fk;
		
		private System.DateTime _Ans_dato;
		
		private System.Nullable<System.DateTime> _Fra_dato;
		
		private bool _Is_Manager;
		
		private decimal _Timetal;
		
		private int _Pay_method;
		
		private string _Pay_method_text;
		
		private System.DateTime _Last_changed;
		
		private string _User_fk;
		
		private EntityRef<Orgunit> _Orgunit;
		
		private EntityRef<Person> _Person;
		
		private EntityRef<User> _User;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSystem_idChanging(int value);
    partial void OnSystem_idChanged();
    partial void OnOpus_idChanging(int value);
    partial void OnOpus_idChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnOrgunit_losid_fkChanging(int value);
    partial void OnOrgunit_losid_fkChanged();
    partial void OnPerson_fkChanging(string value);
    partial void OnPerson_fkChanged();
    partial void OnAns_datoChanging(System.DateTime value);
    partial void OnAns_datoChanged();
    partial void OnFra_datoChanging(System.Nullable<System.DateTime> value);
    partial void OnFra_datoChanged();
    partial void OnIs_ManagerChanging(bool value);
    partial void OnIs_ManagerChanged();
    partial void OnTimetalChanging(decimal value);
    partial void OnTimetalChanged();
    partial void OnPay_methodChanging(int value);
    partial void OnPay_methodChanged();
    partial void OnPay_method_textChanging(string value);
    partial void OnPay_method_textChanged();
    partial void OnLast_changedChanging(System.DateTime value);
    partial void OnLast_changedChanged();
    partial void OnUser_fkChanging(string value);
    partial void OnUser_fkChanged();
    #endregion
		
		public Position()
		{
			this._Orgunit = default(EntityRef<Orgunit>);
			this._Person = default(EntityRef<Person>);
			this._User = default(EntityRef<User>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_System_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int System_id
		{
			get
			{
				return this._System_id;
			}
			set
			{
				if ((this._System_id != value))
				{
					this.OnSystem_idChanging(value);
					this.SendPropertyChanging();
					this._System_id = value;
					this.SendPropertyChanged("System_id");
					this.OnSystem_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Opus_id", DbType="Int NOT NULL")]
		public int Opus_id
		{
			get
			{
				return this._Opus_id;
			}
			set
			{
				if ((this._Opus_id != value))
				{
					this.OnOpus_idChanging(value);
					this.SendPropertyChanging();
					this._Opus_id = value;
					this.SendPropertyChanged("Opus_id");
					this.OnOpus_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Orgunit_losid_fk", DbType="Int NOT NULL")]
		public int Orgunit_losid_fk
		{
			get
			{
				return this._Orgunit_losid_fk;
			}
			set
			{
				if ((this._Orgunit_losid_fk != value))
				{
					if (this._Orgunit.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnOrgunit_losid_fkChanging(value);
					this.SendPropertyChanging();
					this._Orgunit_losid_fk = value;
					this.SendPropertyChanged("Orgunit_losid_fk");
					this.OnOrgunit_losid_fkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Person_fk", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Person_fk
		{
			get
			{
				return this._Person_fk;
			}
			set
			{
				if ((this._Person_fk != value))
				{
					if (this._Person.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnPerson_fkChanging(value);
					this.SendPropertyChanging();
					this._Person_fk = value;
					this.SendPropertyChanged("Person_fk");
					this.OnPerson_fkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ans_dato", DbType="DateTime NOT NULL")]
		public System.DateTime Ans_dato
		{
			get
			{
				return this._Ans_dato;
			}
			set
			{
				if ((this._Ans_dato != value))
				{
					this.OnAns_datoChanging(value);
					this.SendPropertyChanging();
					this._Ans_dato = value;
					this.SendPropertyChanged("Ans_dato");
					this.OnAns_datoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fra_dato", DbType="DateTime")]
		public System.Nullable<System.DateTime> Fra_dato
		{
			get
			{
				return this._Fra_dato;
			}
			set
			{
				if ((this._Fra_dato != value))
				{
					this.OnFra_datoChanging(value);
					this.SendPropertyChanging();
					this._Fra_dato = value;
					this.SendPropertyChanged("Fra_dato");
					this.OnFra_datoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Is_Manager", DbType="Bit NOT NULL")]
		public bool Is_Manager
		{
			get
			{
				return this._Is_Manager;
			}
			set
			{
				if ((this._Is_Manager != value))
				{
					this.OnIs_ManagerChanging(value);
					this.SendPropertyChanging();
					this._Is_Manager = value;
					this.SendPropertyChanged("Is_Manager");
					this.OnIs_ManagerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Timetal", DbType="Decimal(28,10) NOT NULL")]
		public decimal Timetal
		{
			get
			{
				return this._Timetal;
			}
			set
			{
				if ((this._Timetal != value))
				{
					this.OnTimetalChanging(value);
					this.SendPropertyChanging();
					this._Timetal = value;
					this.SendPropertyChanged("Timetal");
					this.OnTimetalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pay_method", DbType="Int NOT NULL")]
		public int Pay_method
		{
			get
			{
				return this._Pay_method;
			}
			set
			{
				if ((this._Pay_method != value))
				{
					this.OnPay_methodChanging(value);
					this.SendPropertyChanging();
					this._Pay_method = value;
					this.SendPropertyChanged("Pay_method");
					this.OnPay_methodChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pay_method_text", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Pay_method_text
		{
			get
			{
				return this._Pay_method_text;
			}
			set
			{
				if ((this._Pay_method_text != value))
				{
					this.OnPay_method_textChanging(value);
					this.SendPropertyChanging();
					this._Pay_method_text = value;
					this.SendPropertyChanged("Pay_method_text");
					this.OnPay_method_textChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Last_changed", DbType="DateTime NOT NULL")]
		public System.DateTime Last_changed
		{
			get
			{
				return this._Last_changed;
			}
			set
			{
				if ((this._Last_changed != value))
				{
					this.OnLast_changedChanging(value);
					this.SendPropertyChanging();
					this._Last_changed = value;
					this.SendPropertyChanged("Last_changed");
					this.OnLast_changedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_fk", DbType="NVarChar(200)")]
		public string User_fk
		{
			get
			{
				return this._User_fk;
			}
			set
			{
				if ((this._User_fk != value))
				{
					if (this._User.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnUser_fkChanging(value);
					this.SendPropertyChanging();
					this._User_fk = value;
					this.SendPropertyChanged("User_fk");
					this.OnUser_fkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Orgunit_Position", Storage="_Orgunit", ThisKey="Orgunit_losid_fk", OtherKey="Los_id", IsForeignKey=true)]
		public Orgunit Orgunit
		{
			get
			{
				return this._Orgunit.Entity;
			}
			set
			{
				Orgunit previousValue = this._Orgunit.Entity;
				if (((previousValue != value) 
							|| (this._Orgunit.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Orgunit.Entity = null;
						previousValue.Positions.Remove(this);
					}
					this._Orgunit.Entity = value;
					if ((value != null))
					{
						value.Positions.Add(this);
						this._Orgunit_losid_fk = value.Los_id;
					}
					else
					{
						this._Orgunit_losid_fk = default(int);
					}
					this.SendPropertyChanged("Orgunit");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Person_Position", Storage="_Person", ThisKey="Person_fk", OtherKey="Cpr", IsForeignKey=true)]
		public Person Person
		{
			get
			{
				return this._Person.Entity;
			}
			set
			{
				Person previousValue = this._Person.Entity;
				if (((previousValue != value) 
							|| (this._Person.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Person.Entity = null;
						previousValue.Positions.Remove(this);
					}
					this._Person.Entity = value;
					if ((value != null))
					{
						value.Positions.Add(this);
						this._Person_fk = value.Cpr;
					}
					else
					{
						this._Person_fk = default(string);
					}
					this.SendPropertyChanged("Person");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="User_Position", Storage="_User", ThisKey="User_fk", OtherKey="Uuid", IsForeignKey=true)]
		public User User
		{
			get
			{
				return this._User.Entity;
			}
			set
			{
				User previousValue = this._User.Entity;
				if (((previousValue != value) 
							|| (this._User.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._User.Entity = null;
						previousValue.Positions.Remove(this);
					}
					this._User.Entity = value;
					if ((value != null))
					{
						value.Positions.Add(this);
						this._User_fk = value.Uuid;
					}
					else
					{
						this._User_fk = default(string);
					}
					this.SendPropertyChanged("User");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Users")]
	public partial class User : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _System_id;
		
		private string _Uuid;
		
		private string _UserId;
		
		private string _Email;
		
		private string _Phone;
		
		private int _Opus_id;
		
		private bool _Updated;
		
		private string _WorkMobile;
		
		private bool _Deleted_in_ad;
		
		private EntitySet<Position> _Positions;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSystem_idChanging(int value);
    partial void OnSystem_idChanged();
    partial void OnUuidChanging(string value);
    partial void OnUuidChanged();
    partial void OnUserIdChanging(string value);
    partial void OnUserIdChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnPhoneChanging(string value);
    partial void OnPhoneChanged();
    partial void OnOpus_idChanging(int value);
    partial void OnOpus_idChanged();
    partial void OnUpdatedChanging(bool value);
    partial void OnUpdatedChanged();
    partial void OnWorkMobileChanging(string value);
    partial void OnWorkMobileChanged();
    partial void OnDeleted_in_adChanging(bool value);
    partial void OnDeleted_in_adChanged();
    #endregion
		
		public User()
		{
			this._Positions = new EntitySet<Position>(new Action<Position>(this.attach_Positions), new Action<Position>(this.detach_Positions));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_System_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int System_id
		{
			get
			{
				return this._System_id;
			}
			set
			{
				if ((this._System_id != value))
				{
					this.OnSystem_idChanging(value);
					this.SendPropertyChanging();
					this._System_id = value;
					this.SendPropertyChanged("System_id");
					this.OnSystem_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Uuid", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string Uuid
		{
			get
			{
				return this._Uuid;
			}
			set
			{
				if ((this._Uuid != value))
				{
					this.OnUuidChanging(value);
					this.SendPropertyChanging();
					this._Uuid = value;
					this.SendPropertyChanged("Uuid");
					this.OnUuidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserId", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string UserId
		{
			get
			{
				return this._UserId;
			}
			set
			{
				if ((this._UserId != value))
				{
					this.OnUserIdChanging(value);
					this.SendPropertyChanging();
					this._UserId = value;
					this.SendPropertyChanged("UserId");
					this.OnUserIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(200)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone", DbType="NVarChar(200)")]
		public string Phone
		{
			get
			{
				return this._Phone;
			}
			set
			{
				if ((this._Phone != value))
				{
					this.OnPhoneChanging(value);
					this.SendPropertyChanging();
					this._Phone = value;
					this.SendPropertyChanged("Phone");
					this.OnPhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Opus_id", DbType="Int NOT NULL")]
		public int Opus_id
		{
			get
			{
				return this._Opus_id;
			}
			set
			{
				if ((this._Opus_id != value))
				{
					this.OnOpus_idChanging(value);
					this.SendPropertyChanging();
					this._Opus_id = value;
					this.SendPropertyChanged("Opus_id");
					this.OnOpus_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Updated", DbType="Bit NOT NULL")]
		public bool Updated
		{
			get
			{
				return this._Updated;
			}
			set
			{
				if ((this._Updated != value))
				{
					this.OnUpdatedChanging(value);
					this.SendPropertyChanging();
					this._Updated = value;
					this.SendPropertyChanged("Updated");
					this.OnUpdatedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WorkMobile", DbType="NVarChar(50)")]
		public string WorkMobile
		{
			get
			{
				return this._WorkMobile;
			}
			set
			{
				if ((this._WorkMobile != value))
				{
					this.OnWorkMobileChanging(value);
					this.SendPropertyChanging();
					this._WorkMobile = value;
					this.SendPropertyChanged("WorkMobile");
					this.OnWorkMobileChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Deleted_in_ad", DbType="Bit NOT NULL")]
		public bool Deleted_in_ad
		{
			get
			{
				return this._Deleted_in_ad;
			}
			set
			{
				if ((this._Deleted_in_ad != value))
				{
					this.OnDeleted_in_adChanging(value);
					this.SendPropertyChanging();
					this._Deleted_in_ad = value;
					this.SendPropertyChanged("Deleted_in_ad");
					this.OnDeleted_in_adChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="User_Position", Storage="_Positions", ThisKey="Uuid", OtherKey="User_fk")]
		public EntitySet<Position> Positions
		{
			get
			{
				return this._Positions;
			}
			set
			{
				this._Positions.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Positions(Position entity)
		{
			this.SendPropertyChanging();
			entity.User = this;
		}
		
		private void detach_Positions(Position entity)
		{
			this.SendPropertyChanging();
			entity.User = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="[log].changes")]
	public partial class change : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _system_id;
		
		private string _change_text;
		
		private System.DateTime _change_date;
		
		private string _action;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onsystem_idChanging(long value);
    partial void Onsystem_idChanged();
    partial void Onchange_textChanging(string value);
    partial void Onchange_textChanged();
    partial void Onchange_dateChanging(System.DateTime value);
    partial void Onchange_dateChanged();
    partial void OnactionChanging(string value);
    partial void OnactionChanged();
    #endregion
		
		public change()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_system_id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long system_id
		{
			get
			{
				return this._system_id;
			}
			set
			{
				if ((this._system_id != value))
				{
					this.Onsystem_idChanging(value);
					this.SendPropertyChanging();
					this._system_id = value;
					this.SendPropertyChanged("system_id");
					this.Onsystem_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_change_text", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string change_text
		{
			get
			{
				return this._change_text;
			}
			set
			{
				if ((this._change_text != value))
				{
					this.Onchange_textChanging(value);
					this.SendPropertyChanging();
					this._change_text = value;
					this.SendPropertyChanged("change_text");
					this.Onchange_textChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_change_date", DbType="DateTime NOT NULL")]
		public System.DateTime change_date
		{
			get
			{
				return this._change_date;
			}
			set
			{
				if ((this._change_date != value))
				{
					this.Onchange_dateChanging(value);
					this.SendPropertyChanging();
					this._change_date = value;
					this.SendPropertyChanged("change_date");
					this.Onchange_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_action", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string action
		{
			get
			{
				return this._action;
			}
			set
			{
				if ((this._action != value))
				{
					this.OnactionChanging(value);
					this.SendPropertyChanging();
					this._action = value;
					this.SendPropertyChanged("action");
					this.OnactionChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="queue.qUsers")]
	public partial class qUser1 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _System_id;
		
		private string _Uuid;
		
		private int _Opus_id;
		
		private string _Change_type;
		
		private System.DateTime _Time_added;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSystem_idChanging(int value);
    partial void OnSystem_idChanged();
    partial void OnUuidChanging(string value);
    partial void OnUuidChanged();
    partial void OnOpus_idChanging(int value);
    partial void OnOpus_idChanged();
    partial void OnChange_typeChanging(string value);
    partial void OnChange_typeChanged();
    partial void OnTime_addedChanging(System.DateTime value);
    partial void OnTime_addedChanged();
    #endregion
		
		public qUser1()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_System_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int System_id
		{
			get
			{
				return this._System_id;
			}
			set
			{
				if ((this._System_id != value))
				{
					this.OnSystem_idChanging(value);
					this.SendPropertyChanging();
					this._System_id = value;
					this.SendPropertyChanged("System_id");
					this.OnSystem_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Uuid", DbType="NVarChar(200)")]
		public string Uuid
		{
			get
			{
				return this._Uuid;
			}
			set
			{
				if ((this._Uuid != value))
				{
					this.OnUuidChanging(value);
					this.SendPropertyChanging();
					this._Uuid = value;
					this.SendPropertyChanged("Uuid");
					this.OnUuidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Opus_id", DbType="Int NOT NULL")]
		public int Opus_id
		{
			get
			{
				return this._Opus_id;
			}
			set
			{
				if ((this._Opus_id != value))
				{
					this.OnOpus_idChanging(value);
					this.SendPropertyChanging();
					this._Opus_id = value;
					this.SendPropertyChanged("Opus_id");
					this.OnOpus_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Change_type", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string Change_type
		{
			get
			{
				return this._Change_type;
			}
			set
			{
				if ((this._Change_type != value))
				{
					this.OnChange_typeChanging(value);
					this.SendPropertyChanging();
					this._Change_type = value;
					this.SendPropertyChanged("Change_type");
					this.OnChange_typeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Time_added", DbType="DateTime NOT NULL")]
		public System.DateTime Time_added
		{
			get
			{
				return this._Time_added;
			}
			set
			{
				if ((this._Time_added != value))
				{
					this.OnTime_addedChanging(value);
					this.SendPropertyChanging();
					this._Time_added = value;
					this.SendPropertyChanged("Time_added");
					this.OnTime_addedChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="queue.qOrgunits")]
	public partial class qOrgunit : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _system_id;
		
		private string _uuid;
		
		private int _los_id;
		
		private string _change_type;
		
		private int _Niveau;
		
		private System.DateTime _time_changed;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onsystem_idChanging(int value);
    partial void Onsystem_idChanged();
    partial void OnuuidChanging(string value);
    partial void OnuuidChanged();
    partial void Onlos_idChanging(int value);
    partial void Onlos_idChanged();
    partial void Onchange_typeChanging(string value);
    partial void Onchange_typeChanged();
    partial void OnNiveauChanging(int value);
    partial void OnNiveauChanged();
    partial void Ontime_changedChanging(System.DateTime value);
    partial void Ontime_changedChanged();
    #endregion
		
		public qOrgunit()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_system_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int system_id
		{
			get
			{
				return this._system_id;
			}
			set
			{
				if ((this._system_id != value))
				{
					this.Onsystem_idChanging(value);
					this.SendPropertyChanging();
					this._system_id = value;
					this.SendPropertyChanged("system_id");
					this.Onsystem_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uuid", DbType="NVarChar(100)")]
		public string uuid
		{
			get
			{
				return this._uuid;
			}
			set
			{
				if ((this._uuid != value))
				{
					this.OnuuidChanging(value);
					this.SendPropertyChanging();
					this._uuid = value;
					this.SendPropertyChanged("uuid");
					this.OnuuidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_los_id", DbType="Int NOT NULL")]
		public int los_id
		{
			get
			{
				return this._los_id;
			}
			set
			{
				if ((this._los_id != value))
				{
					this.Onlos_idChanging(value);
					this.SendPropertyChanging();
					this._los_id = value;
					this.SendPropertyChanged("los_id");
					this.Onlos_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_change_type", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string change_type
		{
			get
			{
				return this._change_type;
			}
			set
			{
				if ((this._change_type != value))
				{
					this.Onchange_typeChanging(value);
					this.SendPropertyChanging();
					this._change_type = value;
					this.SendPropertyChanged("change_type");
					this.Onchange_typeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Niveau", DbType="Int NOT NULL")]
		public int Niveau
		{
			get
			{
				return this._Niveau;
			}
			set
			{
				if ((this._Niveau != value))
				{
					this.OnNiveauChanging(value);
					this.SendPropertyChanging();
					this._Niveau = value;
					this.SendPropertyChanged("Niveau");
					this.OnNiveauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_time_changed", DbType="DateTime NOT NULL")]
		public System.DateTime time_changed
		{
			get
			{
				return this._time_changed;
			}
			set
			{
				if ((this._time_changed != value))
				{
					this.Ontime_changedChanging(value);
					this.SendPropertyChanging();
					this._time_changed = value;
					this.SendPropertyChanged("time_changed");
					this.Ontime_changedChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="queue.qUsers")]
	public partial class qUser : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _System_id;
		
		private string _Uuid;
		
		private int _Opus_id;
		
		private string _Change_type;
		
		private System.DateTime _Time_added;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSystem_idChanging(int value);
    partial void OnSystem_idChanged();
    partial void OnUuidChanging(string value);
    partial void OnUuidChanged();
    partial void OnOpus_idChanging(int value);
    partial void OnOpus_idChanged();
    partial void OnChange_typeChanging(string value);
    partial void OnChange_typeChanged();
    partial void OnTime_addedChanging(System.DateTime value);
    partial void OnTime_addedChanged();
    #endregion
		
		public qUser()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_System_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int System_id
		{
			get
			{
				return this._System_id;
			}
			set
			{
				if ((this._System_id != value))
				{
					this.OnSystem_idChanging(value);
					this.SendPropertyChanging();
					this._System_id = value;
					this.SendPropertyChanged("System_id");
					this.OnSystem_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Uuid", DbType="NVarChar(200)")]
		public string Uuid
		{
			get
			{
				return this._Uuid;
			}
			set
			{
				if ((this._Uuid != value))
				{
					this.OnUuidChanging(value);
					this.SendPropertyChanging();
					this._Uuid = value;
					this.SendPropertyChanged("Uuid");
					this.OnUuidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Opus_id", DbType="Int NOT NULL")]
		public int Opus_id
		{
			get
			{
				return this._Opus_id;
			}
			set
			{
				if ((this._Opus_id != value))
				{
					this.OnOpus_idChanging(value);
					this.SendPropertyChanging();
					this._Opus_id = value;
					this.SendPropertyChanged("Opus_id");
					this.OnOpus_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Change_type", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string Change_type
		{
			get
			{
				return this._Change_type;
			}
			set
			{
				if ((this._Change_type != value))
				{
					this.OnChange_typeChanging(value);
					this.SendPropertyChanging();
					this._Change_type = value;
					this.SendPropertyChanged("Change_type");
					this.OnChange_typeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Time_added", DbType="DateTime NOT NULL")]
		public System.DateTime Time_added
		{
			get
			{
				return this._Time_added;
			}
			set
			{
				if ((this._Time_added != value))
				{
					this.OnTime_addedChanging(value);
					this.SendPropertyChanging();
					this._Time_added = value;
					this.SendPropertyChanged("Time_added");
					this.OnTime_addedChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="queue.qUsers_AD")]
	public partial class qUsers_AD : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _System_id;
		
		private string _Uuid;
		
		private int _EmployeeNumber;
		
		private string _Manager;
		
		private string _Company;
		
		private string _Department;
		
		private string _Office;
		
		private string _StreetAddress;
		
		private string _PostalCode;
		
		private string _City;
		
		private string _Title;
		
		private string _Change_type;
		
		private System.DateTime _Time_added;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSystem_idChanging(int value);
    partial void OnSystem_idChanged();
    partial void OnUuidChanging(string value);
    partial void OnUuidChanged();
    partial void OnEmployeeNumberChanging(int value);
    partial void OnEmployeeNumberChanged();
    partial void OnManagerChanging(string value);
    partial void OnManagerChanged();
    partial void OnCompanyChanging(string value);
    partial void OnCompanyChanged();
    partial void OnDepartmentChanging(string value);
    partial void OnDepartmentChanged();
    partial void OnOfficeChanging(string value);
    partial void OnOfficeChanged();
    partial void OnStreetAddressChanging(string value);
    partial void OnStreetAddressChanged();
    partial void OnPostalCodeChanging(string value);
    partial void OnPostalCodeChanged();
    partial void OnCityChanging(string value);
    partial void OnCityChanged();
    partial void OnTitleChanging(string value);
    partial void OnTitleChanged();
    partial void OnChange_typeChanging(string value);
    partial void OnChange_typeChanged();
    partial void OnTime_addedChanging(System.DateTime value);
    partial void OnTime_addedChanged();
    #endregion
		
		public qUsers_AD()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_System_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int System_id
		{
			get
			{
				return this._System_id;
			}
			set
			{
				if ((this._System_id != value))
				{
					this.OnSystem_idChanging(value);
					this.SendPropertyChanging();
					this._System_id = value;
					this.SendPropertyChanged("System_id");
					this.OnSystem_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Uuid", DbType="NVarChar(200)")]
		public string Uuid
		{
			get
			{
				return this._Uuid;
			}
			set
			{
				if ((this._Uuid != value))
				{
					this.OnUuidChanging(value);
					this.SendPropertyChanging();
					this._Uuid = value;
					this.SendPropertyChanged("Uuid");
					this.OnUuidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmployeeNumber", DbType="Int NOT NULL")]
		public int EmployeeNumber
		{
			get
			{
				return this._EmployeeNumber;
			}
			set
			{
				if ((this._EmployeeNumber != value))
				{
					this.OnEmployeeNumberChanging(value);
					this.SendPropertyChanging();
					this._EmployeeNumber = value;
					this.SendPropertyChanged("EmployeeNumber");
					this.OnEmployeeNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Manager", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
		public string Manager
		{
			get
			{
				return this._Manager;
			}
			set
			{
				if ((this._Manager != value))
				{
					this.OnManagerChanging(value);
					this.SendPropertyChanging();
					this._Manager = value;
					this.SendPropertyChanged("Manager");
					this.OnManagerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Company", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
		public string Company
		{
			get
			{
				return this._Company;
			}
			set
			{
				if ((this._Company != value))
				{
					this.OnCompanyChanging(value);
					this.SendPropertyChanging();
					this._Company = value;
					this.SendPropertyChanged("Company");
					this.OnCompanyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Department", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
		public string Department
		{
			get
			{
				return this._Department;
			}
			set
			{
				if ((this._Department != value))
				{
					this.OnDepartmentChanging(value);
					this.SendPropertyChanging();
					this._Department = value;
					this.SendPropertyChanged("Department");
					this.OnDepartmentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Office", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
		public string Office
		{
			get
			{
				return this._Office;
			}
			set
			{
				if ((this._Office != value))
				{
					this.OnOfficeChanging(value);
					this.SendPropertyChanging();
					this._Office = value;
					this.SendPropertyChanged("Office");
					this.OnOfficeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StreetAddress", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
		public string StreetAddress
		{
			get
			{
				return this._StreetAddress;
			}
			set
			{
				if ((this._StreetAddress != value))
				{
					this.OnStreetAddressChanging(value);
					this.SendPropertyChanging();
					this._StreetAddress = value;
					this.SendPropertyChanged("StreetAddress");
					this.OnStreetAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PostalCode", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
		public string PostalCode
		{
			get
			{
				return this._PostalCode;
			}
			set
			{
				if ((this._PostalCode != value))
				{
					this.OnPostalCodeChanging(value);
					this.SendPropertyChanging();
					this._PostalCode = value;
					this.SendPropertyChanged("PostalCode");
					this.OnPostalCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_City", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
		public string City
		{
			get
			{
				return this._City;
			}
			set
			{
				if ((this._City != value))
				{
					this.OnCityChanging(value);
					this.SendPropertyChanging();
					this._City = value;
					this.SendPropertyChanged("City");
					this.OnCityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this.OnTitleChanging(value);
					this.SendPropertyChanging();
					this._Title = value;
					this.SendPropertyChanged("Title");
					this.OnTitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Change_type", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string Change_type
		{
			get
			{
				return this._Change_type;
			}
			set
			{
				if ((this._Change_type != value))
				{
					this.OnChange_typeChanging(value);
					this.SendPropertyChanging();
					this._Change_type = value;
					this.SendPropertyChanged("Change_type");
					this.OnChange_typeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Time_added", DbType="DateTime NOT NULL")]
		public System.DateTime Time_added
		{
			get
			{
				return this._Time_added;
			}
			set
			{
				if ((this._Time_added != value))
				{
					this.OnTime_addedChanging(value);
					this.SendPropertyChanging();
					this._Time_added = value;
					this.SendPropertyChanged("Time_added");
					this.OnTime_addedChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.v_sofd_medarbejderoverblik")]
	public partial class v_sofd_medarbejderoverblik
	{
		
		private string _Uuid;
		
		private string _UserId;
		
		private string _Email;
		
		private string _Phone;
		
		private string _WorkMobile;
		
		private string _person_name;
		
		private string _Cpr;
		
		private string _Firstname;
		
		private string _Lastname;
		
		private string _privat_gade;
		
		private int _privat_postnr;
		
		private string _privat_by;
		
		private int _Opus_id;
		
		private string _position_name;
		
		private System.DateTime _Ans_dato;
		
		private System.Nullable<System.DateTime> _Fra_dato;
		
		private bool _Is_Manager;
		
		private decimal _Timetal;
		
		private int _Pay_method;
		
		private string _Pay_method_text;
		
		private string _User_fk;
		
		private int _nearmeste_leder;
		
		private string _orgunit_uuid;
		
		private int _Los_id;
		
		private string _org_name;
		
		private string _PayoutUnitUuid;
		
		private System.DateTime _Created_date;
		
		private string _org_phone;
		
		private string _org_email;
		
		private int _Parent_losid;
		
		private string _Los_short_name;
		
		private string _org_gade;
		
		private int _org_postnr;
		
		private string _org_by;
		
		private System.Nullable<long> _Ean;
		
		private System.Nullable<long> _Pnr;
		
		private System.Nullable<long> _Cost_center;
		
		private string _Org_type;
		
		private int _Org_niveau;
		
		public v_sofd_medarbejderoverblik()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Uuid", DbType="NVarChar(200)")]
		public string Uuid
		{
			get
			{
				return this._Uuid;
			}
			set
			{
				if ((this._Uuid != value))
				{
					this._Uuid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserId", DbType="NVarChar(50)")]
		public string UserId
		{
			get
			{
				return this._UserId;
			}
			set
			{
				if ((this._UserId != value))
				{
					this._UserId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(200)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this._Email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone", DbType="NVarChar(200)")]
		public string Phone
		{
			get
			{
				return this._Phone;
			}
			set
			{
				if ((this._Phone != value))
				{
					this._Phone = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WorkMobile", DbType="NVarChar(50)")]
		public string WorkMobile
		{
			get
			{
				return this._WorkMobile;
			}
			set
			{
				if ((this._WorkMobile != value))
				{
					this._WorkMobile = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_person_name", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string person_name
		{
			get
			{
				return this._person_name;
			}
			set
			{
				if ((this._person_name != value))
				{
					this._person_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cpr", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Cpr
		{
			get
			{
				return this._Cpr;
			}
			set
			{
				if ((this._Cpr != value))
				{
					this._Cpr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Firstname", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Firstname
		{
			get
			{
				return this._Firstname;
			}
			set
			{
				if ((this._Firstname != value))
				{
					this._Firstname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lastname", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Lastname
		{
			get
			{
				return this._Lastname;
			}
			set
			{
				if ((this._Lastname != value))
				{
					this._Lastname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_privat_gade", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string privat_gade
		{
			get
			{
				return this._privat_gade;
			}
			set
			{
				if ((this._privat_gade != value))
				{
					this._privat_gade = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_privat_postnr", DbType="Int NOT NULL")]
		public int privat_postnr
		{
			get
			{
				return this._privat_postnr;
			}
			set
			{
				if ((this._privat_postnr != value))
				{
					this._privat_postnr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_privat_by", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string privat_by
		{
			get
			{
				return this._privat_by;
			}
			set
			{
				if ((this._privat_by != value))
				{
					this._privat_by = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Opus_id", DbType="Int NOT NULL")]
		public int Opus_id
		{
			get
			{
				return this._Opus_id;
			}
			set
			{
				if ((this._Opus_id != value))
				{
					this._Opus_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_position_name", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string position_name
		{
			get
			{
				return this._position_name;
			}
			set
			{
				if ((this._position_name != value))
				{
					this._position_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ans_dato", DbType="DateTime NOT NULL")]
		public System.DateTime Ans_dato
		{
			get
			{
				return this._Ans_dato;
			}
			set
			{
				if ((this._Ans_dato != value))
				{
					this._Ans_dato = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fra_dato", DbType="DateTime")]
		public System.Nullable<System.DateTime> Fra_dato
		{
			get
			{
				return this._Fra_dato;
			}
			set
			{
				if ((this._Fra_dato != value))
				{
					this._Fra_dato = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Is_Manager", DbType="Bit NOT NULL")]
		public bool Is_Manager
		{
			get
			{
				return this._Is_Manager;
			}
			set
			{
				if ((this._Is_Manager != value))
				{
					this._Is_Manager = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Timetal", DbType="Decimal(28,10) NOT NULL")]
		public decimal Timetal
		{
			get
			{
				return this._Timetal;
			}
			set
			{
				if ((this._Timetal != value))
				{
					this._Timetal = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pay_method", DbType="Int NOT NULL")]
		public int Pay_method
		{
			get
			{
				return this._Pay_method;
			}
			set
			{
				if ((this._Pay_method != value))
				{
					this._Pay_method = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pay_method_text", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Pay_method_text
		{
			get
			{
				return this._Pay_method_text;
			}
			set
			{
				if ((this._Pay_method_text != value))
				{
					this._Pay_method_text = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_fk", DbType="NVarChar(200)")]
		public string User_fk
		{
			get
			{
				return this._User_fk;
			}
			set
			{
				if ((this._User_fk != value))
				{
					this._User_fk = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nearmeste_leder", DbType="Int NOT NULL")]
		public int nearmeste_leder
		{
			get
			{
				return this._nearmeste_leder;
			}
			set
			{
				if ((this._nearmeste_leder != value))
				{
					this._nearmeste_leder = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_orgunit_uuid", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string orgunit_uuid
		{
			get
			{
				return this._orgunit_uuid;
			}
			set
			{
				if ((this._orgunit_uuid != value))
				{
					this._orgunit_uuid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Los_id", DbType="Int NOT NULL")]
		public int Los_id
		{
			get
			{
				return this._Los_id;
			}
			set
			{
				if ((this._Los_id != value))
				{
					this._Los_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_org_name", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string org_name
		{
			get
			{
				return this._org_name;
			}
			set
			{
				if ((this._org_name != value))
				{
					this._org_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PayoutUnitUuid", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string PayoutUnitUuid
		{
			get
			{
				return this._PayoutUnitUuid;
			}
			set
			{
				if ((this._PayoutUnitUuid != value))
				{
					this._PayoutUnitUuid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Created_date", DbType="DateTime NOT NULL")]
		public System.DateTime Created_date
		{
			get
			{
				return this._Created_date;
			}
			set
			{
				if ((this._Created_date != value))
				{
					this._Created_date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_org_phone", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string org_phone
		{
			get
			{
				return this._org_phone;
			}
			set
			{
				if ((this._org_phone != value))
				{
					this._org_phone = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_org_email", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string org_email
		{
			get
			{
				return this._org_email;
			}
			set
			{
				if ((this._org_email != value))
				{
					this._org_email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Parent_losid", DbType="Int NOT NULL")]
		public int Parent_losid
		{
			get
			{
				return this._Parent_losid;
			}
			set
			{
				if ((this._Parent_losid != value))
				{
					this._Parent_losid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Los_short_name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Los_short_name
		{
			get
			{
				return this._Los_short_name;
			}
			set
			{
				if ((this._Los_short_name != value))
				{
					this._Los_short_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_org_gade", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string org_gade
		{
			get
			{
				return this._org_gade;
			}
			set
			{
				if ((this._org_gade != value))
				{
					this._org_gade = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_org_postnr", DbType="Int NOT NULL")]
		public int org_postnr
		{
			get
			{
				return this._org_postnr;
			}
			set
			{
				if ((this._org_postnr != value))
				{
					this._org_postnr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_org_by", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string org_by
		{
			get
			{
				return this._org_by;
			}
			set
			{
				if ((this._org_by != value))
				{
					this._org_by = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ean", DbType="BigInt")]
		public System.Nullable<long> Ean
		{
			get
			{
				return this._Ean;
			}
			set
			{
				if ((this._Ean != value))
				{
					this._Ean = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pnr", DbType="BigInt")]
		public System.Nullable<long> Pnr
		{
			get
			{
				return this._Pnr;
			}
			set
			{
				if ((this._Pnr != value))
				{
					this._Pnr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cost_center", DbType="BigInt")]
		public System.Nullable<long> Cost_center
		{
			get
			{
				return this._Cost_center;
			}
			set
			{
				if ((this._Cost_center != value))
				{
					this._Cost_center = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Org_type", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Org_type
		{
			get
			{
				return this._Org_type;
			}
			set
			{
				if ((this._Org_type != value))
				{
					this._Org_type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Org_niveau", DbType="Int NOT NULL")]
		public int Org_niveau
		{
			get
			{
				return this._Org_niveau;
			}
			set
			{
				if ((this._Org_niveau != value))
				{
					this._Org_niveau = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="akubiz.v_akubiz_employees")]
	public partial class v_akubiz_employee
	{
		
		private string _User_fk;
		
		private string _Name;
		
		private string _UserId;
		
		private string _Email;
		
		private System.Nullable<long> _Cost_center;
		
		private int _Orgunit_losid_fk;
		
		private string _Person_fk;
		
		private int _manager_opus_id;
		
		public v_akubiz_employee()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_fk", DbType="NVarChar(200)")]
		public string User_fk
		{
			get
			{
				return this._User_fk;
			}
			set
			{
				if ((this._User_fk != value))
				{
					this._User_fk = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserId", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string UserId
		{
			get
			{
				return this._UserId;
			}
			set
			{
				if ((this._UserId != value))
				{
					this._UserId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(200)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this._Email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cost_center", DbType="BigInt")]
		public System.Nullable<long> Cost_center
		{
			get
			{
				return this._Cost_center;
			}
			set
			{
				if ((this._Cost_center != value))
				{
					this._Cost_center = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Orgunit_losid_fk", DbType="Int NOT NULL")]
		public int Orgunit_losid_fk
		{
			get
			{
				return this._Orgunit_losid_fk;
			}
			set
			{
				if ((this._Orgunit_losid_fk != value))
				{
					this._Orgunit_losid_fk = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Person_fk", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Person_fk
		{
			get
			{
				return this._Person_fk;
			}
			set
			{
				if ((this._Person_fk != value))
				{
					this._Person_fk = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_manager_opus_id", DbType="Int NOT NULL")]
		public int manager_opus_id
		{
			get
			{
				return this._manager_opus_id;
			}
			set
			{
				if ((this._manager_opus_id != value))
				{
					this._manager_opus_id = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
