#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL_old.LORA_SOFD_SERVICE
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="LORA_SOFD")]
	public partial class Lora_serviceDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertgod_ledelse_pnr(god_ledelse_pnr instance);
    partial void Updategod_ledelse_pnr(god_ledelse_pnr instance);
    partial void Deletegod_ledelse_pnr(god_ledelse_pnr instance);
    #endregion
		
		public Lora_serviceDataContext() : 
				base(global::DAL_old.Properties.Settings.Default.LORA_SOFDConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public Lora_serviceDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Lora_serviceDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Lora_serviceDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Lora_serviceDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<v_god_ledelse_fælleden> v_god_ledelse_fælledens
		{
			get
			{
				return this.GetTable<v_god_ledelse_fælleden>();
			}
		}
		
		public System.Data.Linq.Table<god_ledelse_pnr> god_ledelse_pnrs
		{
			get
			{
				return this.GetTable<god_ledelse_pnr>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="service.v_god_ledelse_fælleden")]
	public partial class v_god_ledelse_fælleden
	{
		
		private string _orgenhed;
		
		private string _stilling;
		
		private string _User_fk;
		
		private System.Nullable<long> _Pnr;
		
		public v_god_ledelse_fælleden()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_orgenhed", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string orgenhed
		{
			get
			{
				return this._orgenhed;
			}
			set
			{
				if ((this._orgenhed != value))
				{
					this._orgenhed = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stilling", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string stilling
		{
			get
			{
				return this._stilling;
			}
			set
			{
				if ((this._stilling != value))
				{
					this._stilling = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_fk", DbType="NVarChar(200)")]
		public string User_fk
		{
			get
			{
				return this._User_fk;
			}
			set
			{
				if ((this._User_fk != value))
				{
					this._User_fk = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pnr", DbType="BigInt")]
		public System.Nullable<long> Pnr
		{
			get
			{
				return this._Pnr;
			}
			set
			{
				if ((this._Pnr != value))
				{
					this._Pnr = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="service.god_ledelse_pnrs")]
	public partial class god_ledelse_pnr : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _system_id;
		
		private long _pnr;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onsystem_idChanging(int value);
    partial void Onsystem_idChanged();
    partial void OnpnrChanging(long value);
    partial void OnpnrChanged();
    #endregion
		
		public god_ledelse_pnr()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_system_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int system_id
		{
			get
			{
				return this._system_id;
			}
			set
			{
				if ((this._system_id != value))
				{
					this.Onsystem_idChanging(value);
					this.SendPropertyChanging();
					this._system_id = value;
					this.SendPropertyChanged("system_id");
					this.Onsystem_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pnr", DbType="BigInt NOT NULL")]
		public long pnr
		{
			get
			{
				return this._pnr;
			}
			set
			{
				if ((this._pnr != value))
				{
					this.OnpnrChanging(value);
					this.SendPropertyChanging();
					this._pnr = value;
					this.SendPropertyChanged("pnr");
					this.OnpnrChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
